/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ceridwen.infinittonlayoutmockup;

import com.ceridwen.infinittonlayoutmockup.modelviews.LayoutComboBoxModel;
import com.ceridwen.infinittonlayoutmockup.modelviews.LayoutListModel;
import com.ceridwen.infinittonlayoutmockup.datamodel.EmptyButton;
import com.ceridwen.infinittonlayoutmockup.datamodel.ExecutableButton;
import com.ceridwen.infinittonlayoutmockup.datamodel.Layout;
import com.ceridwen.infinittonlayoutmockup.datamodel.LayoutButton;
import com.ceridwen.infinittonlayoutmockup.datamodel.LayoutManager;
import java.util.UUID;
import javax.swing.JButton;

/**
 *
 * @author Matthew.Dovey
 */
public class InfinittonLayoutMockup extends javax.swing.JFrame {

  /**
   * Creates new form LayoutDemo
   */
  public InfinittonLayoutMockup() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLayoutsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLayoutList = new javax.swing.JList<>();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonsPanel = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLayoutName = new javax.swing.JTextField();
        jButtonDetailsPanel = new javax.swing.JPanel();
        jButtonType = new javax.swing.JTabbedPane();
        jEmptyButton = new javax.swing.JPanel();
        jExecutableButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jExecutableName = new javax.swing.JTextField();
        jLayoutButton = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLayoutCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButtonName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonIcon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 400));
        setResizable(false);

        jLayoutsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLayoutsPanel.setPreferredSize(new java.awt.Dimension(400, 192));

        jLayoutList.setModel(new LayoutListModel(LayoutManager.getLayoutManager()));
        jLayoutList.setSelectedIndex(0);
        jLayoutList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jLayoutListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jLayoutList);

        jButtonAdd.setText("+");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDelete.setText("-");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayoutsPanelLayout = new javax.swing.GroupLayout(jLayoutsPanel);
        jLayoutsPanel.setLayout(jLayoutsPanelLayout);
        jLayoutsPanelLayout.setHorizontalGroup(
            jLayoutsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayoutsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayoutsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addGroup(jLayoutsPanelLayout.createSequentialGroup()
                        .addComponent(jButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDelete)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayoutsPanelLayout.setVerticalGroup(
            jLayoutsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayoutsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayoutsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonDelete))
                .addContainerGap())
        );

        jButtonsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton11.setText("jButton1");
        jButton11.setActionCommand("11");
        jButton11.setName(""); // NOI18N
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jButton12.setText("jButton1");
        jButton12.setActionCommand("12");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMouseClicked(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jButton13.setText("jButton1");
        jButton13.setActionCommand("13");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMouseClicked(evt);
            }
        });
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jButton23.setText("jButton1");
        jButton23.setActionCommand("23");
        jButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMouseClicked(evt);
            }
        });
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jButton22.setText("jButton1");
        jButton22.setActionCommand("22");
        jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMouseClicked(evt);
            }
        });
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jButton21.setText("jButton1");
        jButton21.setActionCommand("21");
        jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMouseClicked(evt);
            }
        });
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jButton33.setText("jButton1");
        jButton33.setActionCommand("33");
        jButton33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMouseClicked(evt);
            }
        });
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jButton32.setText("jButton1");
        jButton32.setActionCommand("32");
        jButton32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMouseClicked(evt);
            }
        });
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jButton31.setText("jButton1");
        jButton31.setActionCommand("31");
        jButton31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMouseClicked(evt);
            }
        });
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jButton43.setText("jButton1");
        jButton43.setActionCommand("43");
        jButton43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMouseClicked(evt);
            }
        });
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jButton42.setText("jButton1");
        jButton42.setActionCommand("42");
        jButton42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMouseClicked(evt);
            }
        });
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jButton41.setText("jButton1");
        jButton41.setActionCommand("41");
        jButton41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMouseClicked(evt);
            }
        });
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jButton53.setText("jButton1");
        jButton53.setActionCommand("53");
        jButton53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMouseClicked(evt);
            }
        });
        jButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jButton52.setText("jButton1");
        jButton52.setActionCommand("52");
        jButton52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMouseClicked(evt);
            }
        });
        jButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jButton51.setText("jButton1");
        jButton51.setActionCommand("51");
        jButton51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMouseClicked(evt);
            }
        });
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Layout Name:");

        jLayoutName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLayoutNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jButtonsPanelLayout = new javax.swing.GroupLayout(jButtonsPanel);
        jButtonsPanel.setLayout(jButtonsPanelLayout);
        jButtonsPanelLayout.setHorizontalGroup(
            jButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jButtonsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayoutName))
                    .addGroup(jButtonsPanelLayout.createSequentialGroup()
                        .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jButtonsPanelLayout.createSequentialGroup()
                        .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jButtonsPanelLayout.createSequentialGroup()
                        .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jButtonsPanelLayout.createSequentialGroup()
                        .addComponent(jButton51, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton52, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton53, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jButtonsPanelLayout.createSequentialGroup()
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jButtonsPanelLayout.setVerticalGroup(
            jButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLayoutName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton51, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton52, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton53, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButtonDetailsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonType.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jButtonType.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButtonTypeStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jEmptyButtonLayout = new javax.swing.GroupLayout(jEmptyButton);
        jEmptyButton.setLayout(jEmptyButtonLayout);
        jEmptyButtonLayout.setHorizontalGroup(
            jEmptyButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );
        jEmptyButtonLayout.setVerticalGroup(
            jEmptyButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );

        jButtonType.addTab("Blank", jEmptyButton);

        jLabel4.setText("Executable:");

        jExecutableName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExecutableNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jExecutableButtonLayout = new javax.swing.GroupLayout(jExecutableButton);
        jExecutableButton.setLayout(jExecutableButtonLayout);
        jExecutableButtonLayout.setHorizontalGroup(
            jExecutableButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jExecutableButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jExecutableName, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addContainerGap())
        );
        jExecutableButtonLayout.setVerticalGroup(
            jExecutableButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jExecutableButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jExecutableButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jExecutableName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jButtonType.addTab("Executable", jExecutableButton);

        jLabel5.setText("Layout:");

        jLayoutCombo.setModel(new LayoutComboBoxModel(LayoutManager.getLayoutManager()));
        jLayoutCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLayoutComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayoutButtonLayout = new javax.swing.GroupLayout(jLayoutButton);
        jLayoutButton.setLayout(jLayoutButtonLayout);
        jLayoutButtonLayout.setHorizontalGroup(
            jLayoutButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayoutButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayoutCombo, 0, 510, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayoutButtonLayout.setVerticalGroup(
            jLayoutButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayoutButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayoutButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLayoutCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jButtonType.addTab("Layout", jLayoutButton);

        jLabel1.setText("Button Name:");

        jButtonName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Button Icon:");

        jButtonIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIconActionPerformed(evt);
            }
        });

        jLabel6.setText("Button Type:");

        javax.swing.GroupLayout jButtonDetailsPanelLayout = new javax.swing.GroupLayout(jButtonDetailsPanel);
        jButtonDetailsPanel.setLayout(jButtonDetailsPanelLayout);
        jButtonDetailsPanelLayout.setHorizontalGroup(
            jButtonDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jButtonDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonType)
                    .addGroup(jButtonDetailsPanelLayout.createSequentialGroup()
                        .addGroup(jButtonDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jButtonDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonIcon)
                            .addComponent(jButtonName)))
                    .addGroup(jButtonDetailsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jButtonDetailsPanelLayout.setVerticalGroup(
            jButtonDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jButtonDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jButtonDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jButtonDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonType, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayoutsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayoutsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                .addContainerGap())
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        int index = jLayoutList.getSelectedIndex();

        Layout lay = LayoutManager.getLayoutManager().getLayoutAt(index);

        UpdateButtonDisplay(lay);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
      System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

  private void jLayoutListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jLayoutListValueChanged
    int index = jLayoutList.getSelectedIndex();
    
    Layout layout = LayoutManager.getLayoutManager().getLayoutAt(index);
    
    UpdateButtonDisplay(layout); 
  }//GEN-LAST:event_jLayoutListValueChanged

  private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
    // TODO add your handling code here:
    LayoutManager.getLayoutManager().addLayout(new Layout("New layout"));
    jLayoutList.updateUI();
  }//GEN-LAST:event_jButtonAddActionPerformed

  private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
    // TODO add your handling code here:
    int index = jLayoutList.getSelectedIndex();

    LayoutManager.getLayoutManager().deleteLayoutAt(index);

    jLayoutList.updateUI();
  }//GEN-LAST:event_jButtonDeleteActionPerformed

  private void jLayoutNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLayoutNameActionPerformed
    // TODO add your handling code here:
    int index = jLayoutList.getSelectedIndex();

    UpdateLayoutName(index, jLayoutName.getText());

    jLayoutList.updateUI();
    
    
  }//GEN-LAST:event_jLayoutNameActionPerformed

  private void jButtonNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNameActionPerformed
    int index = jLayoutList.getSelectedIndex();

    UpdateEmptyButton(index, jButtonName.getText(), jButtonIcon.getText());
  }//GEN-LAST:event_jButtonNameActionPerformed

  private void jButtonIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIconActionPerformed
    int index = jLayoutList.getSelectedIndex();

    UpdateEmptyButton(index, jButtonName.getText(), jButtonIcon.getText());
  }//GEN-LAST:event_jButtonIconActionPerformed

  private void jButtonTypeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButtonTypeStateChanged
    int index = jLayoutList.getSelectedIndex();
    
    Layout layout = LayoutManager.getLayoutManager().getLayoutAt(index);
    
    if (layout == null) {
      return;
    }
    
    if (button_a > 0 && button_b > 0) {
      EmptyButton button = layout.getButton(button_a, button_b);

      switch (jButtonType.getSelectedIndex()) {
        case 0:
          if (button instanceof EmptyButton) {          
          } else {
            layout.setButton(button_a, button_b, new EmptyButton(button));
          }
          break;
        case 1:
          if (button instanceof ExecutableButton) {          
          } else {
            button = new ExecutableButton(button);
            layout.setButton(button_a, button_b, button);
            jExecutableName.setText(((ExecutableButton)button).getExecutable());
          }
          break;
        case 2:
          if (button instanceof LayoutButton) {          
          } else {
            button = new LayoutButton(button);
            layout.setButton(button_a, button_b, button);
            jLayoutCombo.setSelectedIndex(LayoutManager.getLayoutManager().getLayoutIndex(((LayoutButton)button).getLayoutUid()));
          }
          break;
      }
    }
  }//GEN-LAST:event_jButtonTypeStateChanged

  private void jExecutableNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExecutableNameActionPerformed
    int index = jLayoutList.getSelectedIndex();
    
    Layout layout = LayoutManager.getLayoutManager().getLayoutAt(index);
    
    if (layout == null) {
      return;
    }
    
    EmptyButton button = layout.getButton(button_a, button_b);
    
    if (button instanceof ExecutableButton) {          
      ((ExecutableButton)button).setExecutable(jExecutableName.getText());
    }
  }//GEN-LAST:event_jExecutableNameActionPerformed

  private void jLayoutComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLayoutComboActionPerformed
    int index = jLayoutList.getSelectedIndex();

    Layout layout = LayoutManager.getLayoutManager().getLayoutAt(index);
    if (layout == null) {
      return;
    }
    
    EmptyButton button = layout.getButton(button_a, button_b);
    
    if (button == null) {
      return;
    }
    
    if (button instanceof LayoutButton) {
      Layout linkedLayout = LayoutManager.getLayoutManager().getLayoutAt(jLayoutCombo.getSelectedIndex());
      if (linkedLayout != null) {
        UUID uid = linkedLayout.getUuid();
        ((LayoutButton)button).setLayoutUid(uid);
      }
    }

  }//GEN-LAST:event_jLayoutComboActionPerformed

  private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
    int index = jLayoutList.getSelectedIndex();
    
    JButton bt = (JButton)evt.getSource();

    String command = bt.getActionCommand();
    int a = Character.getNumericValue(command.charAt(0));
    int b = Character.getNumericValue(command.charAt(1));

    UpdateButtonDetails(index, a, b, bt);
  }//GEN-LAST:event_jButtonActionPerformed

  private void jButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMouseClicked
    if (evt.getClickCount() > 1) {
      int index = jLayoutList.getSelectedIndex();
      
      JButton bt = (JButton)evt.getSource();
      
      String command = bt.getActionCommand();
      int a = Character.getNumericValue(command.charAt(0));
      int b = Character.getNumericValue(command.charAt(1));

      SwitchLayoutByButton(index, a, b);
    }
  }//GEN-LAST:event_jButtonMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(InfinittonLayoutMockup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(InfinittonLayoutMockup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(InfinittonLayoutMockup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(InfinittonLayoutMockup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new InfinittonLayoutMockup().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JPanel jButtonDetailsPanel;
    private javax.swing.JTextField jButtonIcon;
    private javax.swing.JTextField jButtonName;
    private javax.swing.JTabbedPane jButtonType;
    private javax.swing.JPanel jButtonsPanel;
    private javax.swing.JPanel jEmptyButton;
    private javax.swing.JPanel jExecutableButton;
    private javax.swing.JTextField jExecutableName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jLayoutButton;
    private javax.swing.JComboBox<String> jLayoutCombo;
    private javax.swing.JList<String> jLayoutList;
    private javax.swing.JTextField jLayoutName;
    private javax.swing.JPanel jLayoutsPanel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

  private void UpdateButtonDisplay(Layout layout) {
    jLayoutName.setText(layout.getName());
    
    jButton11.setText(layout.getButton(1,1).getName());
    jButton12.setText(layout.getButton(1,2).getName());
    jButton13.setText(layout.getButton(1,3).getName());
    jButton21.setText(layout.getButton(2,1).getName());
    jButton22.setText(layout.getButton(2,2).getName());
    jButton23.setText(layout.getButton(2,3).getName());
    jButton31.setText(layout.getButton(3,1).getName());
    jButton32.setText(layout.getButton(3,2).getName());
    jButton33.setText(layout.getButton(3,3).getName());
    jButton41.setText(layout.getButton(4,1).getName());
    jButton42.setText(layout.getButton(4,2).getName());
    jButton43.setText(layout.getButton(4,3).getName());
    jButton51.setText(layout.getButton(5,1).getName());
    jButton52.setText(layout.getButton(5,2).getName());
    jButton53.setText(layout.getButton(5,3).getName());
    
    UpdateButtonDetails(layout, 0, 0, null);
  }
  
  private void UpdateLayoutName(int index, String name) {
    Layout layout = LayoutManager.getLayoutManager().getLayoutAt(index);

    if (layout != null) {
      layout.setName(name);
    }
  }

  
  private int button_a = 0;
  private int button_b = 0;
  private JButton buttonButton = null;
  
  private void UpdateButtonDetails(int index, int a, int b, JButton jButton) {
    Layout layout = LayoutManager.getLayoutManager().getLayoutAt(index);
    if (layout == null) {
      return;
    }
    
    UpdateButtonDetails(layout, a, b, jButton);
  }
    
  private void UpdateButtonDetails(Layout layout, int a, int b, JButton jButton) {
    button_a = a;
    button_b = b;
    buttonButton = jButton;
    
    if (button_a > 0 && button_b > 0) {
      EmptyButton button = layout.getButton(button_a, button_b);
    
      jButtonName.setText(button.getName());
      jButtonIcon.setText(button.getIcon());

      if (button instanceof ExecutableButton) {
        jButtonType.setSelectedIndex(1);
        jExecutableName.setText(((ExecutableButton)button).getExecutable());
      } else if (button instanceof LayoutButton) {
        jButtonType.setSelectedIndex(2);
        jLayoutCombo.setSelectedIndex(LayoutManager.getLayoutManager().getLayoutIndex(((LayoutButton)button).getLayoutUid()));
      } else {
        jButtonType.setSelectedIndex(0);     
      }
    } else {
      jButtonName.setText("");
      jButtonIcon.setText("");
      jButtonType.setSelectedIndex(0);     
    }
    
    jButtonDetailsPanel.updateUI();
  }
  
  private void UpdateEmptyButton(int index, String name, String icon)
  {
    Layout layout = LayoutManager.getLayoutManager().getLayoutAt(index);
    if (layout == null) {
      return;
    }
    
    if (button_a < 1 || button_b < 1) {
      return;
    }
    if (buttonButton == null) {
      return;
    }
    EmptyButton button = layout.getButton(button_a, button_b);

    button.setName(name);
    button.setIcon(icon);
    buttonButton.setText(name);
    buttonButton.updateUI();
  }

  private void SwitchLayoutByButton(int index, int a, int b) {
    Layout layout = LayoutManager.getLayoutManager().getLayoutAt(index);
    
    EmptyButton button = layout.getButton(a, b);
    
    if (button instanceof LayoutButton) {
      UUID uid = ((LayoutButton) button).getLayoutUid();
      if (uid != null) {
        int newIndex = LayoutManager.getLayoutManager().getLayoutIndex(uid);
        jLayoutList.setSelectedIndex(newIndex);
        jLayoutList.updateUI();
      }
    }
    
    
  }

}
